### ISSUE TITLE
建议添加文章标题的抓取

### ISSUE THREAD

**Issue by simin-in-tw** [Drizzle365/Moments#1]
通过 demo 展示的朋友圈可以看到已经订阅的网站内容，但是列表显示的都是文章摘要，缺少了标题。如果在摘要前面有文章标题的话就更好了，这样看起来也比较好理解。虽然不知道怎么实现，但还是提个建议，万一作者你能实现呢😁😁😁

**Comment by Drizzle365** [comment]
这个地方也考虑过，因为标题直接和内容连接可能会语句不通顺，找到合适的显示方案后会增加这项功能，估计下个版本会完善，感谢提供建议
