### ISSUE TITLE
自动获取博客名称、简介，输入邮箱自动获取头像

### ISSUE THREAD

**Issue by huhexian** [Drizzle365/Moments#7]
![image](https://github.com/Drizzle365/Moments/assets/42113492/e8cf25d0-898c-4c29-a246-9e65692c722e)

能否输入网站域名，然后自动获取网站标题（title）、简介（description）。输入邮箱，如果是QQ邮箱，就获取QQ头像，如果不是，则获取Gravatar头像。

**Comment by Drizzle365** [comment]
好问题，下个版本就加上
